[package]
name = "missing-creator-validation-fix"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "missing_creator_validation_fix"

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
pinocchio = { workspace = true }

[features]
idl-build = ["anchor-lang/idl-build"]
no-entrypoint = []
